android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# SAP BTP SDK for Android - Technical User Credentials
# Obtain these from https://repositories.sap.com/
sap_maven_user=REPLACE_WITH_TECHNICAL_USER_NAME
sap_maven_password=REPLACE_WITH_TECHNICAL_USER_PASSWORD

