pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        maven {
            url "https://repositories.sap.com/maven/"
            credentials {
                username sap_maven_user
                password sap_maven_password
            }
        }
    }
}
rootProject.name = "DroidX"
include ':app'
